# Generated by Django 4.1.3 on 2022-11-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='IsSelected'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(default='fsdfs', max_length=300, unique=True, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
